### ISSUE TITLE
[Bug]: Can't save Data Objects Importer Configuration on Pimcore 6.9.x and data-importer 1.3.1

### ISSUE THREAD

**Issue by fweisflug** [pimcore/data-importer#125]
### Expected behavior

data-importer Data Objects Importer Configuration can be saved (on pimcore 6.9.x).

### Actual behavior

data-importer Data Objects Importer Configuration Save Buttons is disabled and grayed out with the tooltip "config_not_writeable", for new and existing Configurations.

![Screenshot 2021-11-17 at 12 38 29](https://user-images.githubusercontent.com/49750472/142193982-038913cc-07aa-4ca7-8598-6352b6472811.png)

### Steps to reproduce

1. install data-importer 1.3.1 on the latest pimcore 6.9.x
2. create a new Data Objects Importer Configuration
3. try to save this Configuration
4. save button is disabled and grayed out

the offending commit seems to be https://github.com/pimcore/data-importer/commit/7aa4cfcf25f3bc3587d8423932dd2a6a16d618b0
the commit mentions pimcore 10.2. is pimcore 10.2 a requirement now?
the writeable flag in general within the config is never written or set to true, so it defaults to false/disabled(?).
manually adding the writeable flag in "var/config/datahub-configurations.php" enables the save buttons, but is removed with the next save again.

**Comment by danielczestki** [comment]
I have the same problem.

**Comment by danielczestki** [comment]
It should not be only PimCore 10.2 requiremnts. 
In composer.json we have that DataHUb importer requiremnts is:
"pimcore/pimcore": "^6.9 || ^10.0",

@mcop1  @dvesh3

**Comment by dvesh3** [comment]
@danielczestki yes, version 1.3 should be based on Pimcore version 10.2 as it using the `LocationAwareConfigRepository` for configurations which was introduced in Pimcore 10.2 version.

**Comment by dvesh3** [comment]
Fixed by #127

**Comment by danielczestki** [comment]
@dvesh3

What about 1.3.0 ?
Can we use version 1.3.0 with PimCore 6.9 ? I see that it is working = Data Importer Configuration can be saved.

**Comment by dvesh3** [comment]
Strange, if version 1.3.0 working on Pimcore 6.9. As config change was introduced in 1.3 only, please see https://github.com/pimcore/data-importer/pull/103

Please follow these instructions based on Pimcore version https://github.com/pimcore/data-importer/blob/1.3/doc/01_Installation.md

Thanks!

**Comment by fweisflug** [comment]
the commit which broke the functionality was introduced with version 1.3.1 though (https://github.com/pimcore/data-importer/commit/7aa4cfcf25f3bc3587d8423932dd2a6a16d618b0 https://github.com/pimcore/data-importer/compare/v1.3.0...v1.3.1). see my initial comment. that's why 1.3.0 is still working.

the actual functionality is still working even with 1.3.1, just that the config doesn't save/set the "writeable" flag. which is quite a pity tbh.

**Comment by skoch-twocream** [comment]
Hi,

I'm a little confused because I tried to update the bundle for an installation with Pimcore version 10.1.0 (same bug, save not possible). As @fweisflug said, the bundle works fine in older versions.

What is the reason for this line of code?
https://github.com/pimcore/data-importer/commit/7aa4cfcf25f3bc3587d8423932dd2a6a16d618b0#diff-0878cfffd00ee4d3d7d742cad480d2cb121b1bfb0edf1287d01856fac8853106R89

Where is `this.data.general.writeable` filled?
And what is the reason why the bundle can no longer used with Pimcore <10.2 / Are there also any PHP class changes or dependencies?

**Comment by fashxp** [comment]
lets recheck that

**Comment by dvesh3** [comment]
Sorry, for the confusion guys! 

The save button visibility is based on `this.data.general.writeable` property, which was introduced in[ DataHub ](https://github.com/pimcore/data-hub/pull/424/files#diff-b7d2699b4e896dc75c4a5a7ee429706e93312af0a1872fff6a8a1530ed961b57R58). So we had issues where save button was disabled ([because of this line](https://github.com/pimcore/data-importer/blob/1.3/src/Resources/public/js/pimcore/configuration/configItemDataObject.js#L98) ), if you are using older version of Pimcore & DataHub with 1.3 version of this bundle.

Now, we have reverted the Pimcore requirements to support version 6.9 and explicitly setting the `writeable` property if not defined on version 6.9.

**Comment by dvesh3** [comment]
Fixed by #140
