### ISSUE TITLE
[Feature] Allow assigning values to geo data types

### ISSUE THREAD

**Issue by fashxp** [pimcore/data-importer#170]
### Feature description

add operators `as Geopoint` `as GeoBounds` etc. and allow assigning them to corresponding geo data attributes

**Comment by Chris-Gett** [comment]
The feature would be very helpful. I would like to import sales partner data into PIMCORE and thereby import longitude and latitude in order to later forward the data to other systems.

It is possible to export longitude and latitude from the Geopoint data type, so the import should be possible as well.

**Comment by fashxp** [comment]
any PRs are welcome ;-)

**Comment by ghost** [comment]
I'd appreciate this as well, as importing locations is a common and reoccurring task in our company.
