### ISSUE TITLE
Import from XML details

### ISSUE THREAD

**Issue by al3wb** [pimcore/data-importer#31]
Good day! Where can I see detailed examples of the processes of importing data from an XML file? Preferably with screenshots. It is not yet clear how to do this.

**Comment by fashxp** [comment]
does that help? 
[docs](https://pimcore.com/docs/data-importer/current/Configuration/File_Formats.html#page_XML)

**Comment by al3wb** [comment]
I have studied all the official documentation. But it is not clear how to import data from an XML file using the GUI. It is not clear how to get the XML file data for the preview (the file is uploaded to Assets, but it is not displayed in the importer. If you upload it again in the importer, an error is generated that the file is too large).
Below is my screenshot.

![Pimcore Import](https://user-images.githubusercontent.com/13482518/118267768-3f63e380-b4c5-11eb-941f-4ed59b16b904.jpg)

Maybe it is possible to take screenshots of all the steps to import data from XML?

In my example, I'm trying to import an XML feed with products (YML format feed - Yandex Market Language).

An example of the feed used is attached.


[Hoff.ru YML feed.zip](https://github.com/pimcore/data-importer/files/6478632/Hoff.ru.YML.feed.zip)

**Comment by fashxp** [comment]
please see last sentence [here](https://pimcore.com/docs/data-importer/current/Configuration/Import_Preview.html)
>Preview files are saved per user and import configuration in Pimcores tmp directory and **should only be a small extract of the 
actual import files** - due to loading performance and used storage space.

This is also the reason, why the asset defined in the data source is not displayed automatically in the preview - besides that, for other data sources like `push` that would not be possible at all.

An additional feature 'load preview from data source' might be a valuable addition though, PRs are welcome :). 

Nevertheless, there was a bug with loading XMLs when having no schema defined, see https://github.com/pimcore/data-importer/issues/32
Next bugfix release is planned in 2 weeks, until then please use 1.0.x-dev
