### ISSUE TITLE
[Bug]: Load DataObject: mapping by attribute/class/systemkey picks up other classes too

### ISSUE THREAD

**Issue by seybsen** [pimcore/data-importer#329]
### Expected behavior

If one adds a mapping to load a dataobject by class and attribute `SYSTEM Key` only objects matching both the `SYSTEM Key` **and** the class should be loaded.

### Actual behavior

The first(?) object with the `SYSTEM Key` is loaded, regardless of which class the object is.

### Steps to reproduce

On https://demo.pimcore.com/admin/

1. rename dataobject `/Product Data/Manufacturer/Chevrolet` to something else (e.g. `Chevrolette` :wink:)
![image](https://user-images.githubusercontent.com/739688/235873309-3a13ba62-6be3-4b20-b7b7-649c3a5f018c.png)

2. navigate to Datahub Config -> car-import -> Import Settings -> Mappings -> manufacturer -> Transformation Pipeline
![image](https://user-images.githubusercontent.com/739688/235872818-39bdece0-5efb-44b4-8993-cf262d6bdf5d.png)

3. change the `Attribute Name` in Load DataObject from `Name [name]` to `SYSTEM Key`
![image](https://user-images.githubusercontent.com/739688/235873106-c57dba96-1e75-483f-a6cd-229613cfd9eb.png)

The preview shows a dataobject of class `CustomerSegment` which is the issue. It should only find objects of class `Manufacturer`.

**Comment by seybsen** [comment]
Seems to be the same issue as described in: https://github.com/pimcore/data-importer/issues/242

**Comment by mcop1** [comment]
Hello @seybsen , 
I am not sure if I am doing something wrong, but (again) it seems to be working for me. 
I changed the name of https://demo.pimcore.com/admin/login/deeplink?object_59_object to `ChevroletImportTest` and adapted the transformation pipeline according your description:

![grafik](https://github.com/pimcore/data-importer/assets/89011527/927d600d-4bd0-416c-bdb9-6da467965edd)

But the transformation result is empty, which is expected, since we changed the name. 

Obviously I must have missed something?

**Comment by seybsen** [comment]
I can't reproduce it either. There was a new release since I created this issue (and I guess the demo always uses current version): https://github.com/pimcore/data-importer/milestone/35?closed=1

I assume that the issue has already been resolved with the latest version. Thank you!
