### ISSUE TITLE
[Bug] When setting 'System Key' with empty value, import just dies

### ISSUE THREAD

**Issue by fashxp** [pimcore/data-importer#367]
### Expected behavior

get a error message into application logger, and not just having importer stuck

### Actual behavior

```
13:23:37 WARNING   [messenger] Error thrown while handling message Pimcore\Bundle\DataImporterBundle\Messenger\DataImporterMessage. Sending for retry #3 using 4000 ms delay. Error: "Handling "Pimcore\Bundle\DataImporterBundle\Messenger\DataImporterMessage" failed: Pimcore\Model\DataObject\AbstractObject::setKey(): Argument #1 ($key) must be of type string, null given, called in /var/www/html/vendor/pimcore/data-importer/src/Mapping/DataTarget/Direct.php on line 119" ["class" => "Pimcore\Bundle\DataImporterBundle\Messenger\DataImporterMessage","retryCount" => 3,"delay" => 4000,"error" => "Handling "Pimcore\Bundle\DataImporterBundle\Messenger\DataImporterMessage" failed: Pimcore\Model\DataObject\AbstractObject::setKey(): Argument #1 ($key) must be of type string, null given, called in /var/www/html/vendor/pimcore/data-importer/src/Mapping/DataTarget/Direct.php on line 119","exception" => Symfony\Component\Messenger\Exception\HandlerFailedException^ { …}]
```

### Steps to reproduce

- create import with a mapping that assigns a value to the `System Key`
- try to import an empty value to this

**Comment by aryaantony92** [comment]
Not able to reproduce the exact error. I tried with an empty key and got the exception 

Exception: DataObject requires key in /var/www/html/dev/pimcore/pimcore/models/DataObject/AbstractObject.php:688 

![image](https://github.com/pimcore/data-importer/assets/97134765/c71141a5-daba-47a7-aba7-4976cc3678a1)

Also, the importer didn't get stuck because of the exception. The next element was imported.
