### ISSUE TITLE
[Improvement]: big imports fails due to timeouts

### ISSUE THREAD

**Issue by nosovk** [pimcore/data-importer#386]
### Improvement description

When we're running a big import job. Like 300'000 new products. And it fails because of timeouts.
We could fix that by adding [`set_time_limit`](https://www.php.net/manual/en/function.set-time-limit.php) into worker code. In that case

**Comment by kingjia90** [comment]
Thank you for reporting, please provide a PR for it with the exact fixes so that we can review and merge it

**Comment by SamyMP** [comment]
Hi @nosovk, are your timeouts linked to MySQL ? 
We are running into similar issues lately in one of our environments, where we get `MySQL has gone away` or `SQLSTATE[HY000] [2002] Connection refused` when trying to import a lot of dataobjects, we are not sure whether it is due to the server not having enough memory or because of a recent release of the dataimporter

**Comment by nosovk** [comment]
Hm, nope, it's not SQL error, it was from PHP. But I'll check resource load during the import

**Comment by nosovk** [comment]
nope, there is even no spike in resource consumption :(

**Comment by fashxp** [comment]
It seems that you run the command-based execution of the import. That command always runs all the items from the queue - anf if there are a lot, it takes time ... and might hit the execution limit of your php processes. There is not much we can do about that as this is connected to your infrastructure configuration. 

Switching to symfony messenger based execution might solve that issue though, see also https://pimcore.com/docs/platform/Data_Importer/Installation#symfony-messenger-based
