### ISSUE TITLE
Malformed UTF-8 characters, possibly incorrectly encoded (500 Internal Server Error)

### ISSUE THREAD

**Issue by moiashvin** [pimcore/data-importer#56]
Hi,

I am trying to configure an import of CSV using Pimcore X.
CSV has some special french characters e.g. é

CSV (sample, assume 1 column, with header and first row)
Nom catgorie
Batterié

The Preview doesn't work and returns the exception:
Status: 500 | Internal Server Error
URL: /admin/pimcoredataimporter/dataobject/config/load-preview-data
Method: POST
Message: 
        Malformed UTF-8 characters, possibly incorrectly encoded (500 Internal Server Error)

How can I get through this?

Thanks for help.

**Comment by fashxp** [comment]
could you provide an sample CSV please.

**Comment by moiashvin** [comment]
Here is the CSV I used:
https://drive.google.com/file/d/1x-bReU8NtQT5V6OOKUxzVwqoQKmM3WX1/view?usp=sharing

If I remove that "é" it would load the file and preview.

Thanks for helping.

**Comment by fashxp** [comment]
The reason is, that your csv is not utf8 encoded. Right now, only utf8 is supported. 

We would love to see support for more encodings and are happy for any contributions. 
[Here](https://github.com/pimcore/data-importer/blob/1.x/src/DataSource/Interpreter/CsvFileInterpreter.php#L44) would be the place to start.
